### ISSUE TITLE
read function should be more lean

### ISSUE THREAD

**Issue by tk3369** [tk3369/SASLib.jl#31]
The `SASLib.read` function is used to read a file incrementally.  However, there's no reason to return a heavy Dict object (or even a SASDataResult object as described in #30) because all those meta data will be the same for every read function.  It's kind of related to #29... ideally, the user should be able to get all meta information via the handler object.

The objective of this change should be to make `SASLib.read` as lean/efficient as possible.

**Comment by tbeason** [comment]
This is a good direction I think. 

I've also been trying to think of a better way to return the data. I do think a Dict is a bit unwieldy for the data structure (I know you are talking about the entire returned object, not just the data). It feels too hard to work with on its own, so the only way to use it is really to convert it to something else. I'm wondering if moving to a DataFrame, IterableTable, or something more structured might be more useful. Additionally, I find it natural to return some sort of table object because that is what SAS data is naturally stored as - tables.
